[tool.ruff]
line-length = 100
exclude = [
    ".github/*"
]
[tool.ruff.lint]
extend-select = [
    "TD",  # todos
    "I",  # isort
]
ignore = [
    "TD003",  # missing-todo-link. Ignored because we don't require adding tickets to TODOs
]
