# Configuration file for Grafana Loki

# Authentication settings
auth_enabled: false

# Server settings
server:
  http_listen_port: 3100  # Port on which Loki will listen for HTTP requests

# Ingester settings
ingester:
  lifecycler:
    address: 127.0.0.1  # Address of the ingester lifecycler
    ring:
      kvstore:
        store: inmemory  # Key-value store used by the ingester ring
      replication_factor: 1  # Number of replicas for each chunk in the ring
    final_sleep: 0s  # Duration to sleep after ingester loop finishes
  wal:
    dir: "/tmp/wal"  # Directory for write-ahead logs
  chunk_idle_period: 1h  # Duration after which a chunk without new logs is flushed
  max_chunk_age: 1h  # Maximum age of a chunk before it is flushed
  chunk_target_size: 1048576  # Target size for chunks
  chunk_retain_period: 30s  # Minimum duration to retain a chunk
  max_transfer_retries: 0  # Number of retries for chunk transfers (disabled)

# Schema configuration
schema_config:
  configs:
    - from: 2020-01-16  # Starting date for this configuration
      store: boltdb-shipper  # Storage engine for logs
      object_store: filesystem  # Object store for index and chunks
      schema: v11  # Version of the schema used
      index:
        prefix: index_  # Prefix for index files
        period: 24h  # Period for index files

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active  # Directory for active index files
    cache_location: /tmp/loki/boltdb-shipper-cache  # Location of cache files
    cache_ttl: 24h  # Time-to-live for cache entries
    shared_store: filesystem  # Shared store for index and chunks
  filesystem:
    directory: /tmp/loki/chunks  # Directory for storing chunks

# Compactor settings
compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor  # Working directory for compactor
  shared_store: filesystem  # Shared store for compactor

# Limits configuration
limits_config:
  reject_old_samples: true  # Whether to reject old samples
  reject_old_samples_max_age: 24h  # Maximum age for old samples

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 0s  # Maximum look-back period for chunk store

# Table manager settings
table_manager:
  retention_deletes_enabled: false  # Whether retention deletes are enabled
  retention_period: 0s  # Retention period for tables

# Ruler settings
ruler:
  storage:
    type: local  # Type of storage used by the ruler
    local:
      directory: /etc/loki/rules  # Directory for rule files
  rule_path: /tmp/loki/rules-temp  # Path for temporary rule files
  alertmanager_url: http://alertmanager:9093  # URL for Alertmanager
  ring:
    kvstore:
      store: inmemory  # Key-value store used by the ruler ring
  enable_api: true  # Whether API is enabled
  enable_alertmanager_v2: true  # Whether Alertmanager v2 is enabled
